# Rebuilds theme\Views\GridViewGameOverview.xaml from theme\Views\DetailsViewGameOverview.xaml.
#
# The grid view's details panel is the same page as the Details view, with three differences:
#   1. it targets the GridViewGameOverview control;
#   2. it has no cover image (the covers are in the grid beside it);
#   3. it hosts Extra Metadata Loader's standard video player. The fixed variants
#      (VideoLoaderControl_NoControls_NoSound and the like) only play while Details is the active view.
#
# Edit DetailsViewGameOverview.xaml, then run this script. Do not edit GridViewGameOverview.xaml by hand.

$ErrorActionPreference = 'Stop'

$views = Join-Path $PSScriptRoot '..\theme\Views'
$source = Join-Path $views 'DetailsViewGameOverview.xaml'
$target = Join-Path $views 'GridViewGameOverview.xaml'

$text = [IO.File]::ReadAllText($source)

function Replace-Counted([string]$inputText, [string]$pattern, [string]$replacement, [string]$what) {
    $regex = New-Object Text.RegularExpressions.Regex($pattern, [Text.RegularExpressions.RegexOptions]::Singleline)
    $count = $regex.Matches($inputText).Count
    if ($count -eq 0) {
        throw "Nothing matched for: $what. DetailsViewGameOverview.xaml has changed shape; update this script."
    }
    Write-Host ("{0,2} x {1}" -f $count, $what)
    return $regex.Replace($inputText, $replacement)
}

$text = Replace-Counted $text '\{x:Type DetailsViewGameOverview\}' '{x:Type GridViewGameOverview}' 'control type'
# The cover box holds the native cover and ImageRotater's cover; it contains no nested Grid,
# so the first </Grid> after its opening tag is its own. The comment above it goes too.
$text = Replace-Counted $text '\r?\n[ \t]*<!-- Cover, with ImageRotater.*?-->\r?\n[ \t]*<Grid x:Name="LayluCoverBox".*?</Grid>' '' 'cover box removed'
$text = Replace-Counted $text 'ExtraMetadataLoader_VideoLoaderControl_NoControls_NoSound' 'ExtraMetadataLoader_VideoLoaderControl' 'video player name'

$header = @'
    <!-- Laylu: the grid view's details panel. GENERATED by tools\sync-grid-page.ps1 from
         Views\DetailsViewGameOverview.xaml; edit that file and run the script, not this one.
         Differences from the Details page: no cover image, and Extra Metadata Loader's standard
         video player (the fixed variants only play while Details is the active view), so sound and
         the player's control bar follow the extension's own settings here. -->
'@
$text = Replace-Counted $text '    <!-- Laylu: the cinematic page\..*?-->' $header.Replace('$', '$$') 'header comment'

[IO.File]::WriteAllText($target, $text, (New-Object Text.UTF8Encoding($false)))

# Both files must still be well-formed
foreach ($file in $source, $target) {
    [xml]$null = Get-Content -Raw -LiteralPath $file
    Write-Host "well-formed: $(Split-Path $file -Leaf)"
}
